#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control xfce
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/settings.install \
    > ./debian/${CODENAME_SAFE}-xfce-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/settings.postinst \
    > ./debian/${CODENAME_SAFE}-xfce-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/livesettings.install \
    > ./debian/${CODENAME_SAFE}-xfce-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-xfce-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/settings.postrm \
    > ./debian/${CODENAME_SAFE}-xfce-settings.postrm

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-xfce-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./debtemplate/livesettings.service \
    > ./debian/${CODENAME_SAFE}-xfce-livesettings.service


## templating

[ -d ./etc ] && rm -rf ./etc
[ -d ./live ] && rm -rf ./live
[ -d ./schemas ] && rm -rf ./schemas
cp -a ./template/etc .
cp -a ./template/live .
cp -a ./template/schemas .





sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ./template/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml \
    > ./etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    template/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml \
    > ./etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml

grub_template xfce


exit 0
