#!/bin/sh
# postinst script for #PACKAGE#

set -e


case "$1" in
    configure)
        ## dconf ##
        cp -af /usr/share/2021-03-xfce-settings/etc/dconf          /etc
        ## grub ##
        cp -af /usr/share/2021-03-xfce-settings/etc/default        /etc
        ## NetworkManager ##
        # cp -af /usr/share/2021-03-xfce-settings/etc/NetworkManager           /etc
        ## iwd ##
        # cp -af /usr/share/2021-03-xfce-settings/etc/iwd                      /etc
        ## schemas ##
        cp -afv /usr/share/2021-03-xfce-settings/schemas           /usr/share/glib-2.0
        ## skel ##
        #cp -af /usr/share/2021-03-xfce-settings/etc/skel/config    /etc/skel/.config
        cp -af /usr/share/2021-03-xfce-settings/etc/skel/gtkrc-2.0 /etc/skel/.gtkrc-2.0
        cp -af /usr/share/2021-03-xfce-settings/etc/skel/dmrc      /etc/skel/.dmrc
        ## xdg  ##
        cp -af /usr/share/2021-03-xfce-settings/etc/xdg            /etc
        ## settings ##
        glib-compile-schemas /usr/share/glib-2.0/schemas
        dconf update
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
