#!/bin/sh
# postinst script for #PACKAGE#

set -e

set_sddm_session() {
        sed -e "s/User=/User=siducer/g" \
            -e "s/Session=/Session=xfce.desktop/g" \
            /etc/sddm-*.conf \
            > /etc/sddm.conf
}


case "$1" in
    configure)
        set_sddm_session
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask whiteroom-xfce-livesettings.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled whiteroom-xfce-livesettings.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable whiteroom-xfce-livesettings.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state whiteroom-xfce-livesettings.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask whiteroom-xfce-livesettings.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled whiteroom-xfce-livesettings.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable whiteroom-xfce-livesettings.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state whiteroom-xfce-livesettings.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/whiteroom-xfce-livesettings" ]; then
		update-rc.d whiteroom-xfce-livesettings defaults >/dev/null
		invoke-rc.d whiteroom-xfce-livesettings start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start whiteroom-xfce-livesettings.service >/dev/null || true
fi
# End automatically added section


exit 0
