#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop whiteroom-xfce-livesettings.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/whiteroom-xfce-livesettings" ]; then
	invoke-rc.d whiteroom-xfce-livesettings stop || exit $?
fi
# End automatically added section
